/*
 * SonarScanner for .NET
 * Copyright (C) SonarSource Sàrl
 * mailto: info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

namespace SonarScanner.MSBuild.PackagingTest;

[TestClass]
public class ZipTest
{
    [TestInitialize]
    public void Initialize() =>
        TestOrchestration.InitializeTestClass();

    [TestMethod]
    public void ValidateFileList_Net() =>
        Verifier.UnzippedFileList(null, "sonar-scanner-*-net.zip").Should().BeEquivalentTo([
            "Google.Protobuf.dll",
            "ICSharpCode.SharpZipLib.dll",
            "Microsoft.CodeCoverage.IO.dll",
            "Newtonsoft.Json.dll",
            "SonarQube.Analysis.xml",
            "SonarScanner.MSBuild.Common.dll",
            "SonarScanner.MSBuild.dll",
            "SonarScanner.MSBuild.PostProcessor.dll",
            "SonarScanner.MSBuild.PreProcessor.dll",
            "SonarScanner.MSBuild.runtimeconfig.json",
            "SonarScanner.MSBuild.Shim.dll",
            "SonarScanner.MSBuild.Tasks.dll",
            "SonarScanner.MSBuild.TFS.dll",
            "Targets/",
            "Targets/SonarQube.Integration.ImportBefore.targets",
            "Targets/SonarQube.Integration.targets",
            "Licenses/",
            "Licenses/LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/",
            "Licenses/THIRD_PARTY_LICENSES/Google.Protobuf-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/Microsoft.CodeCoverage.IO-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/Newtonsoft.Json-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/SharpZipLib-LICENSE.txt"
        ]);

    [TestMethod]
    public void ValidateFileList_NetFramework() =>
        Verifier.UnzippedFileList(null, "sonar-scanner-*-net-framework.zip").Should().BeEquivalentTo([
            "Google.Protobuf.dll",
            "ICSharpCode.SharpZipLib.dll",
            "Microsoft.CodeCoverage.IO.dll",
            "Microsoft.Win32.Primitives.dll",
            "netstandard.dll",
            "Newtonsoft.Json.dll",
            "SonarQube.Analysis.xml",
            "SonarScanner.MSBuild.Common.dll",
            "SonarScanner.MSBuild.exe",
            "SonarScanner.MSBuild.exe.config",
            "SonarScanner.MSBuild.PostProcessor.dll",
            "SonarScanner.MSBuild.PreProcessor.dll",
            "SonarScanner.MSBuild.Shim.dll",
            "SonarScanner.MSBuild.Tasks.dll",
            "SonarScanner.MSBuild.TFS.dll",
            "SonarScanner.MSBuild.TFSProcessor.exe",
            "SonarScanner.MSBuild.TFSProcessor.exe.config",
            "System.AppContext.dll",
            "System.Buffers.dll",
            "System.Collections.Concurrent.dll",
            "System.Collections.dll",
            "System.Collections.NonGeneric.dll",
            "System.Collections.Specialized.dll",
            "System.ComponentModel.dll",
            "System.ComponentModel.EventBasedAsync.dll",
            "System.ComponentModel.Primitives.dll",
            "System.ComponentModel.TypeConverter.dll",
            "System.Console.dll",
            "System.Data.Common.dll",
            "System.Diagnostics.Contracts.dll",
            "System.Diagnostics.Debug.dll",
            "System.Diagnostics.FileVersionInfo.dll",
            "System.Diagnostics.Process.dll",
            "System.Diagnostics.StackTrace.dll",
            "System.Diagnostics.TextWriterTraceListener.dll",
            "System.Diagnostics.Tools.dll",
            "System.Diagnostics.TraceSource.dll",
            "System.Diagnostics.Tracing.dll",
            "System.Drawing.Primitives.dll",
            "System.Dynamic.Runtime.dll",
            "System.Globalization.Calendars.dll",
            "System.Globalization.dll",
            "System.Globalization.Extensions.dll",
            "System.IO.Compression.dll",
            "System.IO.Compression.ZipFile.dll",
            "System.IO.dll",
            "System.IO.FileSystem.dll",
            "System.IO.FileSystem.DriveInfo.dll",
            "System.IO.FileSystem.Primitives.dll",
            "System.IO.FileSystem.Watcher.dll",
            "System.IO.IsolatedStorage.dll",
            "System.IO.MemoryMappedFiles.dll",
            "System.IO.Pipes.dll",
            "System.IO.UnmanagedMemoryStream.dll",
            "System.Linq.dll",
            "System.Linq.Expressions.dll",
            "System.Linq.Parallel.dll",
            "System.Linq.Queryable.dll",
            "System.Memory.dll",
            "System.Net.Http.dll",
            "System.Net.NameResolution.dll",
            "System.Net.NetworkInformation.dll",
            "System.Net.Ping.dll",
            "System.Net.Primitives.dll",
            "System.Net.Requests.dll",
            "System.Net.Security.dll",
            "System.Net.Sockets.dll",
            "System.Net.WebHeaderCollection.dll",
            "System.Net.WebSockets.Client.dll",
            "System.Net.WebSockets.dll",
            "System.Numerics.Vectors.dll",
            "System.ObjectModel.dll",
            "System.Reflection.dll",
            "System.Reflection.Extensions.dll",
            "System.Reflection.Primitives.dll",
            "System.Resources.Reader.dll",
            "System.Resources.ResourceManager.dll",
            "System.Resources.Writer.dll",
            "System.Runtime.CompilerServices.Unsafe.dll",
            "System.Runtime.CompilerServices.VisualC.dll",
            "System.Runtime.dll",
            "System.Runtime.Extensions.dll",
            "System.Runtime.Handles.dll",
            "System.Runtime.InteropServices.dll",
            "System.Runtime.InteropServices.RuntimeInformation.dll",
            "System.Runtime.Numerics.dll",
            "System.Runtime.Serialization.Formatters.dll",
            "System.Runtime.Serialization.Json.dll",
            "System.Runtime.Serialization.Primitives.dll",
            "System.Runtime.Serialization.Xml.dll",
            "System.Security.Claims.dll",
            "System.Security.Cryptography.Algorithms.dll",
            "System.Security.Cryptography.Csp.dll",
            "System.Security.Cryptography.Encoding.dll",
            "System.Security.Cryptography.Primitives.dll",
            "System.Security.Cryptography.X509Certificates.dll",
            "System.Security.Principal.dll",
            "System.Security.SecureString.dll",
            "System.Text.Encoding.dll",
            "System.Text.Encoding.Extensions.dll",
            "System.Text.RegularExpressions.dll",
            "System.Threading.dll",
            "System.Threading.Overlapped.dll",
            "System.Threading.Tasks.dll",
            "System.Threading.Tasks.Extensions.dll",
            "System.Threading.Tasks.Parallel.dll",
            "System.Threading.Thread.dll",
            "System.Threading.ThreadPool.dll",
            "System.Threading.Timer.dll",
            "System.ValueTuple.dll",
            "System.Xml.ReaderWriter.dll",
            "System.Xml.XDocument.dll",
            "System.Xml.XmlDocument.dll",
            "System.Xml.XmlSerializer.dll",
            "System.Xml.XPath.dll",
            "System.Xml.XPath.XDocument.dll",
            "Targets/",
            "Targets/SonarQube.Integration.ImportBefore.targets",
            "Targets/SonarQube.Integration.targets",
            "Licenses/",
            "Licenses/LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/",
            "Licenses/THIRD_PARTY_LICENSES/Google.Protobuf-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/Microsoft.CodeCoverage.IO-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/Microsoft.Win32.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/netstandard-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/Newtonsoft.Json-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/SharpZipLib-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.AppContext-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Buffers-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Collections-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Collections.Concurrent-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Collections.NonGeneric-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Collections.Specialized-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ComponentModel-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ComponentModel.EventBasedAsync-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ComponentModel.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ComponentModel.TypeConverter-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Console-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Data.Common-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.Contracts-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.Debug-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.FileVersionInfo-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.Process-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.StackTrace-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.TextWriterTraceListener-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.Tools-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.TraceSource-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Diagnostics.Tracing-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Drawing.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Dynamic.Runtime-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Globalization-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Globalization.Calendars-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Globalization.Extensions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.Compression-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.Compression.ZipFile-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.FileSystem-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.FileSystem.DriveInfo-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.FileSystem.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.FileSystem.Watcher-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.IsolatedStorage-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.MemoryMappedFiles-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.Pipes-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.IO.UnmanagedMemoryStream-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Linq-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Linq.Expressions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Linq.Parallel-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Linq.Queryable-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Memory-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Http-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.NameResolution-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.NetworkInformation-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Ping-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Requests-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Security-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.Sockets-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.WebHeaderCollection-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.WebSockets-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Net.WebSockets.Client-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Numerics.Vectors-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ObjectModel-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Reflection-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Reflection.Extensions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Reflection.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Resources.Reader-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Resources.ResourceManager-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Resources.Writer-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.CompilerServices.Unsafe-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.CompilerServices.VisualC-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Extensions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Handles-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.InteropServices-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.InteropServices.RuntimeInformation-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Numerics-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Serialization.Formatters-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Serialization.Json-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Serialization.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Runtime.Serialization.Xml-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Claims-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Cryptography.Algorithms-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Cryptography.Csp-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Cryptography.Encoding-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Cryptography.Primitives-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Cryptography.X509Certificates-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.Principal-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Security.SecureString-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Text.Encoding-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Text.Encoding.Extensions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Text.RegularExpressions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Overlapped-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Tasks-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Tasks.Extensions-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Tasks.Parallel-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Thread-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.ThreadPool-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Threading.Timer-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.ValueTuple-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.ReaderWriter-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.XDocument-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.XmlDocument-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.XmlSerializer-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.XPath-LICENSE.txt",
            "Licenses/THIRD_PARTY_LICENSES/System.Xml.XPath.XDocument-LICENSE.txt",
        ]);

    [TestMethod]
    [DataRow("sonar-scanner-*-net.zip", 7)]             // 7x dll
    [DataRow("sonar-scanner-*-net-framework.zip", 8)]   // 6x dll + 2x exe
    public void ValidateSignatures(string pattern, int expectedFileCount)
    {
        TestOrchestration.RunOnlyOnReleaseBranch();
        using var archive = Verifier.UnzipFile(null, pattern);
        var dlls = archive.Entries.Where(Verifier.IsSonarBinary).ToArray();
        dlls.Should().HaveCount(expectedFileCount);
        foreach (var dll in dlls)
        {
            Verifier.ValidateSignature(dll);
        }
    }
}
