user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    server {
    # port to listen on. Can also be set to an IP:PORT
        listen 4443 ssl;
        ssl_certificate /manual-tests/system-trusted.crt;
        ssl_certificate_key /manual-tests/system-trusted.key;

        location / {
            proxy_pass http://localhost:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
    # port to listen on. Can also be set to an IP:PORT
        listen 5443 ssl;
        ssl_certificate /manual-tests/untrusted.crt;
        ssl_certificate_key /manual-tests/untrusted.key;

        location / {
            proxy_pass http://localhost:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
    # port to listen on. Can also be set to an IP:PORT
        listen 6443 ssl;
        ssl_certificate /manual-tests/truststore.crt;
        ssl_certificate_key /manual-tests/truststore.key;

        location / {
            proxy_pass http://localhost:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
    # port to listen on. Can also be set to an IP:PORT
        listen 7443 ssl;
        ssl_certificate /manual-tests/defaultpass.crt;
        ssl_certificate_key /manual-tests/defaultpass.key;

        location / {
            proxy_pass http://localhost:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
