<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Expected.xmlcoverage" />
    <None Remove="Resources\Sample.coverage" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Expected.xmlcoverage">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Sample.coverage">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SonarScanner.MSBuild.Common\SonarScanner.MSBuild.Common.csproj" />
    <ProjectReference Include="..\..\src\SonarScanner.MSBuild.Shim\SonarScanner.MSBuild.Shim.csproj" />
    <ProjectReference Include="..\..\src\SonarScanner.MSBuild.TFS\SonarScanner.MSBuild.TFS.csproj" />
    <ProjectReference Include="..\TestUtilities\TestUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NSubstitute" />
  </ItemGroup>
</Project>
