parameters:
  - name: vmImage
    type: string
  - name: name
    type: string

stages:
  - stage: qa_${{ lower(parameters.name) }}
    displayName: "QA - ${{ parameters.name }}:"
    dependsOn: build
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: uts
        workspace:
          clean: all
        displayName: "Run UTs"
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Run dotnet test'
            inputs:
              command: 'test'
              arguments: '--framework net9.0 --filter "TestCategory!=NoUnixNeedsReview&TestCategory!=No${{ parameters.name }}"'
              testRunTitle: UTs ${{ parameters.name }}
            env:
              ARTIFACTORY_USER: $(ARTIFACTORY_PRIVATE_READER_USERNAME)
              ARTIFACTORY_PASSWORD: $(ARTIFACTORY_PRIVATE_READER_ACCESS_TOKEN)

      - template: ./its-jobs.yml
        parameters:
          initSteps:
            - powershell: $(Build.SourcesDirectory)/scripts/ci-self-signed-certificate.ps1
              displayName: "Create self-signed certificate"
            # On Linux/MacOS we need to update the execution permissions for the ScannerCLI
            - script: chmod -R +x $(Build.SourcesDirectory)/build/sonarscanner-net/sonar-scanner-*/bin
              name: scannerPermissions
              displayName: "Update Scanner permissions"
          matrix:
            LATEST_RELEASE:
              PRODUCT: "SonarQube"
              SQ_VERSION: "LATEST_RELEASE"
              TEST_INCLUDE: "**/sonarqube/ScannerTest*,**/sonarqube/SslTest*,**/sonarqube/JreProvisioningTest*,**/sonarqube/ParameterTest*,**/sonarqube/IncrementalPRAnalysisTest*,**/sonarqube/CppTest*,**/sonarqube/CodeCoverageTest*,**/sonarqube/ProxyTest*"
            Cloud:
              PRODUCT: "SonarCloud"
              SQ_VERSION: ""
              TEST_INCLUDE: "**/sonarcloud/*"
            Others:
              PRODUCT: "others"
              SQ_VERSION: ""
              TEST_INCLUDE: "**/others/*"
