parameters:
  - name: vmImage
    type: string
  - name: name
    type: string

stages:
  - stage: qa_${{ lower(parameters.name) }}
    displayName: "QA - ${{ parameters.name }}:"
    dependsOn: build
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: uts
        workspace:
          clean: all
        displayName: "Run UTs"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              arguments: '--framework net9.0  --filter TestCategory!=NoLinux'
            env:
              ARTIFACTORY_USER: $(ARTIFACTORY_PRIVATE_READER_USERNAME)
              ARTIFACTORY_PASSWORD: $(ARTIFACTORY_PRIVATE_READER_ACCESS_TOKEN)

      - template: ./its-jobs.yml
        parameters:
          # TODO: Remove with SCAN4NET-315
          failIfNoTests: false
