$fullBuildOutputDir = "$PSScriptRoot\..\build"
$scannerCliVersion = "4.8.0.2856"
$scannerCliAssemblyName = "sonar-scanner-cli-$ScannerCliVersion"
$scannerCliArtifact = "$scannerCliAssemblyName.zip"
$scannerCliDownloadDir = "$fullBuildOutputDir\temp"
