$fullBuildOutputDir = "$PSScriptRoot\..\build"
$scannerCliVersion = "4.7.0.2747"
$scannerCliAssemblyName = "sonar-scanner-cli-$ScannerCliVersion"
$scannerCliArtifact = "$scannerCliAssemblyName.zip"
$scannerCliDownloadDir = "$fullBuildOutputDir\temp"