//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQube.TeamBuild.PreProcessor.Roslyn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoslynResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoslynResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQube.TeamBuild.PreProcessor.Roslyn.RoslynResources", typeof(RoslynResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating local NuGet repository. Source: {0}.
        /// </summary>
        internal static string CreatingRepository {
            get {
                return ResourceManager.GetString("CreatingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing required analyzer NuGet packages....
        /// </summary>
        internal static string InstallingPackages {
            get {
                return ResourceManager.GetString("InstallingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating package: {0}-{1}.
        /// </summary>
        internal static string LocatingPackage {
            get {
                return ResourceManager.GetString("LocatingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No analyzer packages were specified.
        /// </summary>
        internal static string NoAnalyzerPackages {
            get {
                return ResourceManager.GetString("NoAnalyzerPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package installed.
        /// </summary>
        internal static string PackageInstalled {
            get {
                return ResourceManager.GetString("PackageInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package installation failed: {0}.
        /// </summary>
        internal static string PackageInstallFailed {
            get {
                return ResourceManager.GetString("PackageInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer packages installed.
        /// </summary>
        internal static string PackagesInstalled {
            get {
                return ResourceManager.GetString("PackagesInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package conflict: {0}.
        /// </summary>
        internal static string ResolveFileConflict {
            get {
                return ResourceManager.GetString("ResolveFileConflict", resourceCulture);
            }
        }
    }
}
