name: Build and Test

on:
  push:
    branches: [master, 'branch-*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  build:
    name: Build
    runs-on: warp-custom-dotnet-bubble-ci
    permissions:
      id-token: write
      contents: read
    env:
      NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Prepare
        id: prepare
        uses: ./.github/actions/prepare
        with:
          nuget-packages-path: ${{ env.NUGET_PACKAGES }}

      - name: Generate SBOM
        run: dotnet CycloneDX SonarScanner.MSBuild.sln -t --json -o Packaging\Binaries

      - name: Build
        run: dotnet build SonarScanner.MSBuild.sln --no-restore -c Release /m

      - name: Zip .NET packages
        shell: powershell
        env:
          FULL_VERSION: ${{ steps.prepare.outputs.FULL_VERSION }}
        run: |
          function Zip-Assemblies([string]$Source, [string]$Destination) {
              # Don't use Compress-Archive because https://github.com/SonarSource/sonar-scanner-msbuild/issues/2086
              tar -c -a -C "$Source" --options "zip:compression-level=9" -f "$Destination" *
          }

          Zip-Assemblies "Packaging/Binaries/Net" "Packaging/Binaries/sonar-scanner-$env:FULL_VERSION-net.zip"
          Zip-Assemblies "Packaging/Binaries/Net-Framework" "Packaging/Binaries/sonar-scanner-$env:FULL_VERSION-net-framework.zip"

      - name: Upload Binaries artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Binaries
          path: Packaging/Binaries
          retention-days: 1
          if-no-files-found: error
