name: release
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      releaseId:
        type: string
        description: Release ID
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false

jobs:
  release:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
    steps:
      - name: Setup JFrog
        uses: SonarSource/jfrog-setup-wrapper@3.0.0-1
        with:
          artifactoryRoleSuffix: promoter
      - name: Get the version
        id: get_version
        run: |
          IFS=. read major minor patch build <<< "${{ inputs.version || github.event.release.tag_name }}"
          echo "build=${build}" >> $GITHUB_OUTPUT
      - name: Promote Artifact
        if: ${{ inputs.dryRun != true }}
        id: jfrog
        run: |
          jfrog rt bpr --status released sonar-scanner-msbuild ${{ steps.get_version.outputs.build }} sonarsource-public-releases
