name: sonar-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      releaseId:
        description: 'GitHub Release ID'
        required: true
        type: string
      dryRun:
        description: 'Dry run mode (draft release)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v7
    with:
      publishToBinaries: true
      slackChannel: squad-dotnet-s4net
      version: ${{ inputs.version }}
      releaseId: ${{ inputs.releaseId }}
      dryRun: ${{ inputs.dryRun }}
